### ISSUE TITLE
Support basic CRUD operations for TNS entries

### ISSUE THREAD

**Issue by avindra** [dcarbone/tns-parser#2]
I have a use case where I would need to modify the entries in the `tnsnames.ora` file. Currently, it seems like the only way to do this is by hacking `serialize` and `unserialize`.

In addition, I need to be able to do so across multiple processes without contention issues. This should be fairly easy to implement. I'm thinking:
- `<tnsfile>.lock` being created at the start of each transaction
- When the transaction is finished, delete the lock file
- Any transaction which updates the file should `usleep` until the lock file is removed (with a timeout, upon which a `TransactionTimeoutException` is thrown)

I'd be willing to take a stab at this, as I need this ASAP for one of my own projects. I can also create tests for it.

What are your thoughts?

**Comment by dcarbone** [comment]
I'm absolutely up for a feature like this, seems like it could definitely be useful!  I personally do not have time to do these changes in the near future, so if you want to have a go at it I'm all for it!

**Comment by avindra** [comment]
Still fleshing out some more tests, and will start once a few more are in place.

**Comment by avindra** [comment]
As an FYI I am moving on to another company and will no longer require this. If anyone wants to take it up, please feel free. I have not started on it.
